### ISSUE TITLE
ResourceStatusReason: 'Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 83ZC2T5KCEF1G2HY;)

### ISSUE THREAD

**Issue by Arka21Pal** [Arka21Pal/aws-practice#20]
It seems that S3 doesn't have the necessary permissions to invoke the Lambda function? I am unable to understand why this is the case since I have configured the type `AWS::Lambda::Permission` to be able to invoke lambda.

```
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt InsertLambdaFunction.Arn
#       FunctionName: "InsertLambdaFunction"
      Principal: s3.amazonaws.com
#       SourceArn: !Sub 'arn:aws:s3:::${WebsiteBucketName}'
      SourceArn: !GetAtt WebsiteBucket.Arn
    DependsOn: InsertLambdaFunction
```
